#!/bin/bash
#launch Rhel8 t2.med 
sudo useradd username
sudo echo "username ALL=(ALL) NOPASSWD:ALL"| sudo tee /etc/sudoers.d/username
su username
cd /opt
sudo yum install wget -y
sudo yum install git -y
sudo wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
sudo yum install jdk-8u131-linux-x64.rpm -y
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip
sudo unzip sonarqube-7.8.zip
sudo rm -rf sonarqube-7.8.zip
sudo mv sonarqube-7.8 sonarqube
sudo chown -R username:username /opt/sonarqube
sudo chmod -R 775 /opt/sonarqube/
cd /opt/sonarqube/bin/linux-x86-64/
sh sonar.sh start
